/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial1g2;

import java.util.Scanner;

public class App {

    /*
     * Implemente una funcion llamada calcularTotalImpuestos que cumpla con las
     * siguientes caracteristicas
     * Recibe:
     * - Una cadena de caracteres que representa la decada (70, 80, 90, 00, 10, 20,
     * Otra)
     * - Un entero que representa avaluo del vehiculo
     * Retorna:
     * - Un entero representando el valor total a pagar de los impuestos
     * Controlar errores retornando -1
     */
    // ------------------------------------------------------------------

    public static int calcularTotalImpuestos(String decada, int avaluo) {
        try {
            int impuestoRodamiento = 0;
            int seguro = 0;
            int totalPagar = 0;
            if (avaluo <= 0 && !decada.equals("90") && !decada.equals("00") && !decada.equals("10") && !decada.equals("20")) {
                return -1;
            }
            switch (decada) {
                case "90":
                    impuestoRodamiento = (int) (avaluo * 0.0409);
                    seguro = (int) (avaluo * 0.00816);
                    break;
                case "00":
                    impuestoRodamiento = (int) (avaluo * 0.0434);
                    seguro = (int) (avaluo * 0.00798);
                    break;
                case "10":
                    impuestoRodamiento = (int) (avaluo * 0.0493);
                    seguro = (int) (avaluo * 0.00712);
                    break;
                case "20":
                    impuestoRodamiento = (int) (avaluo * 0.05680);
                    seguro = (int) (avaluo * 0.00699);
                    break;
                default:
                    break;
            }
            totalPagar = (int) impuestoRodamiento + seguro;
            return (int) totalPagar;
        } catch (Exception e) {
            return -1;
        }
    }

    // ------------------------------------------------------------

    public static void main(String[] args) {
        try {
            String decada = "";
            int avaluo = 0;
            int cantidadVehiculos = 0;
            Scanner sc = new Scanner(System.in);
            System.out.println("¿Cuántos vehículos desea calcular?");
            cantidadVehiculos = sc.nextInt();
            sc.nextLine();

            for (int i = 1; i <= cantidadVehiculos; i++) {
                System.out.println("Vehículo " + i + ": \nIngrese la decada del modelo del vehículo (90, 00, 10, 20):");
                decada = sc.nextLine();
                sc.nextLine();

                System.out.println("Ingrese el avalúo del vehículo:");
                avaluo = sc.nextInt();
                sc.nextLine();

                System.out.println("Década del modelo: " + decada + "\nAvalúo: " + avaluo + " COP \n" + "Total a pagar: " + calcularTotalImpuestos(decada, avaluo) + " COP\n");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
}
